name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install system dependencies
          run: |
            sudo apt-get update -y
            sudo apt-get install -y libasound2-dev
    - uses: actions/checkout@v3
    - name: Fmt
      run: cargo fmt
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
